# -*- coding: utf-8 -*-
"""Cleaned data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ulFRr3wIu_9PqHxPG-hk3qbRWTf0kIHH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("diabetes.csv")
df.head()

df.info()
df.describe()

"""# 1) Handling Missing Data"""

missing_before = df.isnull().sum()
missing_before

columns_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for col in columns_with_zero:
    print(col, (df[col] == 0).sum())

df[columns_with_zero] = df[columns_with_zero].replace(0, np.nan)
df.isnull().sum()

plt.figure(figsize=(8,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap (Before Imputation)")
plt.show()

before_imputation = df.isnull().sum()

for col in columns_with_zero:
    df[col] = df[col].fillna(df[col].median())

after_imputation = df.isnull().sum()
after_imputation

comparison_df = pd.DataFrame({
    "Missing Values (Before)": before_imputation,
    "Missing Values (After)": after_imputation
})

comparison_df

plt.figure(figsize=(8,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap (After Imputation)")
plt.show()

"""### Justification for Missing Data Handling

In this dataset, missing values appeared as zeros in medical features such as
Glucose, BloodPressure, SkinThickness, Insulin, and BMI.
Since zero is not a medically valid value for these measurements,
we treated them as missing values.

We chose Median Imputation instead of Mean because:
- The dataset contains outliers (as shown in boxplots).
- The median is more robust to extreme values.
- It preserves the distribution better than the mean.

Deletion was not used because removing rows would reduce the dataset size
and potentially remove important medical information.

#2) Outlier Treatment
"""

df.describe()

import pandas as pd
from google.colab import files

uploaded = files.upload()
df = pd.read_csv("diabetes.csv")

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['BloodPressure'])
plt.title('BloodPressure - Before Treatment')
plt.xlabel('BloodPressure')
plt.show()

sns.boxplot(x=df['Glucose'])
plt.title('Glucose - Before Treatment')
plt.xlabel('Glucose')
plt.show()

sns.boxplot(x=df['Age'])
plt.title('Age - Before Treatment')
plt.xlabel('Age')
plt.show()

sns.boxplot(x=df['Pregnancies'])
plt.title('Before Treatment')
plt.show()

sns.boxplot(x=df['Insulin'])
plt.title('Before Treatment')
plt.show()

sns.boxplot(x=df['SkinThickness'])
plt.title('Before Treatment')
plt.show()

sns.boxplot(x=df['BMI'])
plt.title('Before Treatment')
plt.show()

sns.boxplot(x=df['DiabetesPedigreeFunction'])
plt.title('Before Treatment')
plt.show()

columns_to_fix = ['Pregnancies', 'Insulin', 'SkinThickness',
                  'BMI', 'DiabetesPedigreeFunction', 'BloodPressure' ,  'Age' , 'Glucose']

for column in columns_to_fix:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)

sns.boxplot(x=df['BloodPressure'])
plt.title('BloodPressure - After Treatment')
plt.xlabel('BloodPressure')
plt.show()

sns.boxplot(x=df['Glucose'])
plt.title('Glucose - After Treatment')
plt.xlabel('Glucose')
plt.show()

sns.boxplot(x=df['Age'])
plt.title('Age - After Treatment')
plt.xlabel('Age')
plt.show()

sns.boxplot(x=df['Pregnancies'])
plt.title('After Treatment')
plt.show()

sns.boxplot(x=df['Insulin'])
plt.title('After Treatment')
plt.show()

sns.boxplot(x=df['SkinThickness'])
plt.title('After Treatment')
plt.show()

sns.boxplot(x=df['BMI'])
plt.title('After Treatment')
plt.show()

sns.boxplot(x=df['DiabetesPedigreeFunction'])
plt.title('After Treatment')
plt.show()

df.describe()

"""## **3) Feature Transformation**"""

from sklearn.preprocessing import StandardScaler

features = df.drop("Outcome", axis=1)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

df_scaled = pd.DataFrame(scaled_features, columns=features.columns)

df_scaled["Outcome"] = df["Outcome"]

df_scaled.head()

"""# The effect of your cleaning using Distribution Plots or comparison tables"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.boxplot(data=df.drop("Outcome", axis=1))
plt.title("Before Scaling")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df_scaled.drop("Outcome", axis=1))
plt.title("After Scaling")
plt.xticks(rotation=45)
plt.show()

"""# Documentation table"""

summary = pd.DataFrame({
    "Step": [
        "Replaced zeros with NaN",
        "Filled missing values with Median",
        "Outlier treatment using IQR",
        "Feature Scaling using StandardScaler"
    ],
    "Description": [
        "Converted invalid zero values to NaN",
        "Replaced missing values with column median",
        "Clipped extreme values using IQR method",
        "Standardized numerical features"
    ]
})

summary

"""# Prepared by :
# Zaina Akram Hassouna 220236864
# Sara Ahmed Al-shorafa 220235514
# Leena Nehad Al-Wer 220237820
"""

df.to_csv('Cleaned_Data.csv', index=False)

from google.colab import files
files.download('Cleaned_Data.csv')